
# parameters that must be natural integers and their default values
NONZERO_INTEGER_PARAMETERS:
  page: 1
  per_page: 25



# These are the actions logged in the user history - the log_items table
ACTION_ACTIVATE: 0
ACTION_ADD_ROLE: 1
ACTION_REMOVE_ROLE: 2
ACTION_SUSPEND: 3
ACTION_UNSUSPEND: 4
ACTION_BAN: 5
ACTION_WARN: 6
ACTION_RENAME: 7
ACTION_PASSWORD_RESET: 8
ACTION_NEW_EMAIL: 9
ACTION_TROUBLESHOOT: 10


##### For dumping the seed database and NOT clearing emails on stage

# users who have webdavs or asked to be added
# or who have problematic works which need testing
DUMP_SEEDS: [
            "Amancham", "Anneli", "ariana_paris", "astolat", "Atalan", "awils1",
            "aworldinside", "bingeling", "Cesy", "cesytest", "Celandine",
            "Chandri", "daymarket",  "eel", "elz", "erda", "Enigel",
            "fairywearsbootz", "hele", "Hope", "insomniac_amy", "Jaetion",
            "jennyst", "Jenn_Calaelen", "justira", "jetta_e_rus", "karanguni",
            "Kitsune", "krytella", "Lal", "lim", "Lisztful", "macey_muse", "mumble",
            "open_doors", "Rebecca", "RKlyne", "Rustler", "Shay_Guy", "Sidra",
            "signalvsnoise", "staranise", "Stowaway", "testy", "Tel",
            "tomatopudding", "tuff_ghost", "velocitygrass", "xparrot", "yaobikuni",
            "zelempa", "zoemathemata", "Zooey_Glass", "zlabya", "zz9pzza"
]

# seeds who want their email address preserved for testing
DUMP_EMAIL: [
          "admin-amelia", "admin-elz", "admin-emilie", "admin-franny",
          "admin-kielix", "admin-shalott", "admin-sidra",
          "Amancham", "astolat", "aworldinside", "bingeling", "cesy",
          "cesytest", "elz", "Enigel", "hele", "Lal", "mumble", "open_doors",
          "Sidra", "testy", "velocitygrass", "xparrot", "Zooey_Glass" ,
          "zz9pzza"
]

# a bunch of bigger collections (>250 works)
# probably would be scooped up anyway, but just in case
DUMP_COLLECTION_SEEDS: [
          "yuletide2009", "ladieschoice", "yuletidemadness2009", "female_focus",
          "crossgen_slash", "PornBattleIX", "Remix2010", "yuletide2010", "fic_promptly",
          "chromatic_yuletide_2010", "Fandom_Stocking", "yuletidemadness2010", "PornBattleXI",
          "Remix2011", "PornBattleXII"
]


# only use if you are running your app completely in a subfolder of your domain
#PRODUCTION_URL_ROOT: "/archive"



# bug-reporting site for the archive -- we use 16bugs; if you use something else,
# you will need to change feedbacks_controller.rb and abuse_reports_controller.rb
# to properly send to your own support tool.
BUGS_SITE: 'url for your 16bugs site like https://otw.16bugs.com'
BUGS_USER: 'admin username for your 16bugs site which should only be put into your local.yml on your production server'
BUGS_PASSWORD: 'admin password for your 16bugs site which should only be put into your local.yml on your production server'




#Cached Count Expiration
COUNT_EXPIRATION: 40.minutes







