PERFORM_DELIVERIES:
 name: Deliver Emails
 default: false
 type: boolean

DEFAULT_LANGUAGE_NAME:
  default: English
  name: "Default Language Name"

DEFAULT_LANGUAGE_SHORT:
  default: en
  name: "Default Language Short Name"

DEFAULT_LOCALE_ISO:
  default: en
  name: "Default Locale ISO"

DEFAULT_LOCALE_NAME:
  default: "English (US)"
  name: "Default Locale Name"

BCRYPT_COST:
 name: cost
 default: 14

SUPPORTED_EXTERNAL_URLS:
  default:
    - jpg
    - png
    - gif
  name: "Supported External URLS"
  type: list

PHRASEAPP_ENABLE:
 default: false
 name: "PhraseApp Enable"

PHRASEAPP_TOKEN:
 default: token
 name: "PhraseApp Token"

SESSION_SECRET:
 name: Session Secret
 default: 898f6d0363863ec79d782238cd1c5767636d712cc0d138238bcd5bfc9d2672fb852380050e52c03a0401175d909c09dba48512a119d46b126a84c2dd05716eb5

ABUSE_ADDRESS:
  default: abuse@example.org
  name: "Abuse Email Address"

ADMIN_ADDRESS:
  default: admin@example.org
  name: "Admin Email Address"

ERROR_ADDRESS:
  default: errors@example.org
  name: "Error Email Address"

ERROR_PREFIX:
  default:
    - ERROR
  name: "Error Email Address"

FEEDBACK_ADDRESS:
  default: feedback@example.org
  name: "Feedback Email Address"

QUESTION_ADDRESS:
  default: question@example.org
  name: "Question Email Address"
  type: string

RETURN_ADDRESS:
  default: do-not-reply@example.org
  name: "Return Email Address"

SMTP_AUTHENTICATION:
  default: plain
  name: "SMTP Autentication Type"

SMTP_DOMAIN:
  default: localhost
  name: "SMTP Domain"

SMTP_PORT:
  default: 25
  name: "SMTP Port"
  type: integer

SMTP_SERVER:
  default: localhost
  name: "SMTP Server"

SPAM_ALERT_ADDRESS:
  default: spam@example.org
  name: "Spam Alert Email Address"

SPAM_THRESHOLD:
  default: 15
  name: "Spam Threshold"
  type: integer

SUPPORT_ADDRESS:
  default: do-not-reply@example.org
  name: "Support Email Address"

USE_SMTP_AUTH:
  default: false
  name: "Use SMTP Authentication"

WEBMASTER_ADDRESS:
  default: webmaster@example.org
  name: "Webmaster Email Address"

session_key:
  default: _otwarchive_session
  name: "Session Key"

ACCOUNT_CREATION_ENABLED:
  default: false
  name: "Enable Account Creation"
  type: boolean

ALT_LOGO:
  default: "Example Logo ALT Text"
  name: "ALT Logo Text"

APP_HOST:
  default: archiveofourown.org
  name: "Application Host"

APP_NAME:
  default: "Example Archive"
  name: "Application Name"

APP_SHORT_NAME:
  default: AO3
  name: "Application Short Name"

DAYS_TO_PURGE_UNACTIVATED:
  default: 7
  name: "Purge Inactive Accounts After X Days"
  type: integer

DEVELOPMENT_PROFILING_ENABLED:
  default: true
  name: "Enable Development Profiling"
  type: boolean

ELASTICSEARCH_1_URL:
  default: "http://localhost:9200"
  name: "Secondary Elastic Search URL"

ELASTICSEARCH_URL:
  default: "http://localhost:9200"
  name: "Primary Elastic Search URL"

BCRYPT:
 name: "Use BCRYPT"
 default: true

INVITE_FROM_QUEUE_ENABLED:
  default: true
  name: "Enable Invite From Queue"
  type: boolean

INVITE_FROM_QUEUE_FREQUENCY:
  default: 7
  name: "Frequency to Invite From Queue"
  type: integer

INVITE_FROM_QUEUE_NUMBER:
  default: 10
  name: "Number to Invite From Queue"
  type: integer

LOGO:
  default: logo.png
  name: "Logo Graphic Filename"

MAX_USER_INVITE_REQUEST:
  default: 10
  name: "Maximum Number of Invites Requestable"
  type: integer

MEMCACHED_URL:
  default: "127.0.0.1"
  name: "Memcached URL"

ORPHANING_ALLOWED:
  default: true
  name: "Allow Orphaning"
  type: boolean

OTWALT_LOGO:
  default: "Example ORG Logo ALT Text"
  name: "ORG Logo ALT Text"

OTWLOGO:
  default: OTWLogo.png
  name: "ORG Logo Filename"

REVISION:
  default: "Sample String"
  name: "Archive Revision"

SANITIZER_VERSION:
  default: 1
  name: "Sanitizer Version"
  type: integer

app_url:
  default: "http://www.example.org"
  name: "Application URL"

ABUSE_REPORTS_PER_WORK_MAX:
  default: 5
  name: "Maximum Abuse Reports Per Work"
  type: integer

COMMENT_THREAD_MAX_DEPTH:
  default: 5
  name: "Maximum Comment Thread Depth"
  type: integer

CONTENT_MAX:
  default: 510000
  name: "Content Maximum Length"
  type: integer

CONTENT_MAX_DISPLAYED:
  default: 500000
  name: "Content Maximum Displayed Length"
  type: integer

CONTENT_MIN:
  default: 10
  name: "Content Minimum Length"
  type: integer

DAYS_TO_SAVE_PROCESSED:
  default: 56
  name: "Days to save redis results"
  type: integer

DESCRIPTION_MAX:
  default: 500
  name: "Pseud Description Maximum Length"
  type: integer

FAQ_MAX:
  default: 200000
  name: "FAQ Maximum Length"
  type: integer

FEEDBACK_SUMMARY_MAX:
  default: 107
  name: "Feedback Summary Maximum Length"
  type: integer

FEEDBACK_SUMMARY_MAX_DISPLAYED:
  default: 100
  name: "Feedback Summary Maximum Displayed Length"
  type: integer

ICON_ALT_MAX:
  default: 250
  name: "Icon ALT Maximum Length"
  type: integer

ICON_COMMENT_MAX:
  default: 50
  name: "Icon Comment Maximum Length"
  type: integer

IMPORT_MAX_CHAPTERS:
  default: 200
  name: "Maximum Number of Chapters Importable"
  type: integer

IMPORT_MAX_WORKS:
  default: 25
  name: "Maximum Number of Works Importable"
  type: integer

IMPORT_MAX_WORKS_BY_ARCHIVIST:
  default: 500
  name: "Maximum Number of Works Importable By Archivist"
  type: integer

INFO_MAX:
  default: 100000
  name: "Information Maximum Length"
  type: integer

ITEMS_PER_PAGE:
  default: 25
  name: "Items Displayed Per Page"
  type: integer

LOGIN_LENGTH_MAX:
  default: 40
  name: "Login Maximum Length"
  type: integer

LOGIN_LENGTH_MIN:
  default: 3
  name: "Login Minimum Length"
  type: integer

LOGNOTE_MAX:
  default: 1250
  name: "Log Note Maximum Length"
  type: integer

LOGNOTE_MIN:
  default: 5
  name: "Log Note Minimum Length"
  type: integer

MAX_FAVORITE_TAGS:
  default: 20
  name: "Maximum Favorite Tags To Show"
  type: integer

MAX_KUDOS_TO_SHOW:
  default: 50
  name: "Maximum Kudos To Show"
  type: integer

MAX_OPTIONS_TO_SHOW:
  default: 20
  name: "Maximum Options To Show"
  type: integer

MAX_SIGNUPS_FOR_LIVE_SUMMARY:
  default: 20
  name: "Maximum Live Challenge Summary Signup"
  type: integer

NAME_LENGTH_MAX:
  default: 100
  name: "Name Maximum Length"
  type: integer

NAME_LENGTH_MIN:
  default: 1
  name: "Name Minimum Length"
  type: integer

NOTES_MAX:
  default: 5000
  name: "Notes Maximum Length"
  type: integer

NUMBER_OF_ITEMS_VISIBLE_IN_DASHBOARD:
  default: 5
  name: "Items Visible On Dashboard"
  type: integer

NUMBER_OF_ITEMS_VISIBLE_ON_HOMEPAGE:
  default: 3
  name: "Items Displayed On HomePage"
  type: integer

OPTIONS_TO_SHOW:
  default: 3
  name: "Options to Show"
  type: integer

PASSWORD_LENGTH_MAX:
  default: 40
  name: "Password Maximum Length"
  type: integer

PASSWORD_LENGTH_MIN:
  default: 6
  name: "Password Minimum Length"
  type: integer

POTENTIAL_MATCHES_MAX:
  default: 50
  name: "Maximum Potential Matches"
  type: integer

POTENTIAL_MATCHES_MIN:
  default: 10
  name: "Minimum Potential Matches"
  type: integer

POTENTIAL_MATCHES_PERCENT:
  default: 10
  name: "Maximum Percentage of Participants to Match"
  type: integer

PREPROCESS_COUNT_ANY_DIVISOR:
  default: 10
  name: "Preprocess Count Any Divisor"
  type: integer

PREPROCESS_COUNT_ANY_MIN:
  default: 10
  name: "Preprocess Count Any Minimum"
  type: integer

PREPROCESS_COUNT_TAGS_DIVISOR:
  default: 10
  name: "Preprocess Count Tags Divisor"
  type: integer

PREPROCESS_COUNT_TAGS_MAX:
  default: 10
  name: "Preprocess Tags MAX"
  type: integer

PROFILE_ABOUT_ME_MAX:
  default: 2000
  name: "Profile About Me Maximum Length"
  type: integer

PROFILE_LOCATION_MAX:
  default: 255
  name: "Profile Location Maximum Length"
  type: integer

PROFILE_TITLE_MAX:
  default: 255
  name: "Profile Title Maximum Length"
  type: integer

PROMPTS_MAX:
  default: 10
  name: "Maximum Prompts Allowed"
  type: integer

PROMPT_MEME_PROMPTS_MAX:
  default: 50
  name: "Maximum Prompt MEME Allowed"
  type: integer

PROMPT_TAGS_MAX:
  default: 20
  name: "Maximum Number of Tags in Prompts"
  type: integer

SUMMARY_MAX:
  default: 1250
  name: "Summary Maximum Length"
  type: integer

TAGS_IN_CLOUD:
  default: 200
  name: "Tag Cloud Limit"
  type: integer

TAGS_PER_LINE:
  default: 12
  name: "Tags Per Line"
  type: integer

TAG_LIST_LIMIT:
  default: 300
  name: "Tag List Limit"
  type: integer

TAG_MAX:
  default: 100
  name: "Tag Maximum Length"
  type: integer

TITLE_MAX:
  default: 255
  name: "Title Maximum Length"
  type: integer

TITLE_MIN:
  default: 1
  name: "Title Minimum Length"
  type: integer

WARNING_CATEGORY_NAME:
  default: "Archive Warning"
  name: "Warning Category Name"

WARNING_CHAN_TAG_NAME:
  default: Underage
  name: "Underage Warning Name"

WARNING_DEATH_TAG_NAME:
  default: "Major Character Death"
  name: "Death Warning Tag Name"

WARNING_DEFAULT_TAG_DISPLAY_NAME:
  default: "Choose Not To Use Archive Warnings"
  name: "Warning Default Tag Name"

WARNING_DEFAULT_TAG_NAME:
  default: "Choose Not To Use Archive Warnings"
  name: "Warning Default Tag Name"

WARNING_NONCON_TAG_NAME:
  default: Rape/Non-Con
  name: "Rape/Non-Con Warning Tag Name"

WARNING_NONE_TAG_DISPLAY_NAME:
  default: "No Archive Warnings Apply"
  name: "No Warning Display Tag Name"

WARNING_NONE_TAG_NAME:
  default: "No Archive Warnings Apply"
  name: "No Warnings Tag Name"

WARNING_VIOLENCE_TAG_NAME:
  default: "Graphic Depictions Of Violence"
  name: "Violence Warning Tag Name"

comment_max:
  default: 4300
  name: "Comment Maximum Length"
  type: integer


# This is used to determine how many recent items
# to cache for recent lookups -- eg if we want to
# provide a "ten most recent" items to browse.
# used in CacheFinds module -- include CacheFinds in a model
# and the methods Model.recent and Model.last(#) will be
# enabled, cached on production/test environments.
MAX_RECENT:
 name: Maximum Recent Cached
 default: 20
 type: integer

# This is used to determine how many works or how many authors have to be
# present in order for anonymous or mystery works to begin being displayed
ANONYMOUS_THRESHOLD_COUNT:
 name: Anonymous Threshold
 default: 10
 type: integer

# This is used to determine how tolerant of changes to be when determining
# whether a comment should go back into moderation after editing or not
COMMENT_MODERATION_THRESHOLD:
 name: Content Moderation Threshold
 default: 10
 type: integer

# variables for Askimet http://akismet.com/
AKISMET_KEY:
 name: Askimet Key
 default: 6833ee7298cf

AKISMET_NAME:
 name: Askimet Name (URL)
 default: http://transformativeworks.org

DEFENSIO_KEY:
 name: Defensio Key
 default: 521476c0edf3ac96eab7e297f6fb92c8

DEFENSIO_NAME:
 name: Defensio Name (URL)
 default: http://archiveofourown.org

COUNT_EXPIRATION:
 name: "Count Expiration"
 default: 40.minutes



FIELDS_ALLOWING_LESS_THAN:
  default:
    - query
    - words
    - kudos
    - hits
    - date
    - bookmarkable_date
    - word_count
    - bookmarks_count
    - comments_count
    - kudos_count
    - revised_at
  name: "Fields Allowing Less Than"
  type: list




# Only the following fields are allowed to have HTML. In all others,
# all HTML tags will be stripped.
#
# NOTE: the exact HTML tags and attributes and protocols allowed are defined in
#  initializers/sanitizer_config.rb
#
# If you add a new field to this list, you need to:
# - make sure that every model that contains the field also has a matching field "[fieldname]_sanitizer_version"
#  Example:
#   add_column :chapters, :content_sanitizer_version, :integer, :default => 0, :null => false, :limit => 2
#
# - make sure in the model that this field is NOT accessible (eg "attr_protected :content_sanitizer_version")
#
# - when you load the field you should use sanitize_field(object, :fieldname)
#
# This will ensure that the field has been sanitized with the latest version of the sanitizer.
#
FIELDS_ALLOWING_CSS:
  default:
    - content
    - endnotes
    - notes
  name: "Fields Allowing CSS"
  type: list

FIELDS_ALLOWING_HTML:
  default:
    - about_me
    - comment
    - content
    - description
    - endnotes
    - faq
    - intro
    - note
    - notes
    - rules
    - signup_instructions_general
    - signup_instructions_offers
    - signup_instructions_requests
    - summary
    - screencast
  name: "Fields Allowing HTML"
  type: list

FIELDS_ALLOWING_HTML_ENTITIES:
  default:
    - title
  name: "Fields Allowing HTML Entities"
  type: list

FIELDS_ALLOWING_VIDEO_EMBEDS:
  default:
    - content
  name: "Fields Allowing Video Embedding"
  type: list

SUPPORTED_CSS_SHORTHAND_PROPERTIES:
  default:
    - background
    - border
    - column
    - cue
    - font
    - layer-background
    - layout-grid
    - list-style
    - margin
    - marker
    - outline
    - overflow
    - padding
    - page-break
    - pause
    - scrollbar
    - text
    - transform
    - transition
  name: "Supported Shorthand CSS Properties"
  type: list

SUPPORTED_CSS_KEYWORDS:
  default:
    - "!important"
    - url
  name: "Supported CSS Keywords"
  type: list

SUPPORTED_CSS_PROPERTIES:
  default:
    - "-replace"
    - "-use-link-source"
    - accelerator
    - alignment-adjust
    - alignment-baseline
    - appearance
    - azimuth
    - baseline-shift
    - behavior
    - binding
    - bookmark-label
    - bookmark-level
    - bookmark-target
    - bottom
    - box-align
    - box-direction
    - box-flex
    - box-flex-group
    - box-lines
    - box-orient
    - box-pack
    - box-shadow
    - box-sizing
    - caption-side
    - clear
    - clip
    - color
    - color-profile
    - content
    - counter-increment
    - counter-reset
    - crop
    - cue
    - cue-after
    - cue-before
    - cursor
    - direction
    - display
    - dominant-baseline
    - drop-initial-after-adjust
    - drop-initial-after-align
    - drop-initial-before-adjust
    - drop-initial-before-align
    - drop-initial-size
    - drop-initial-value
    - elevation
    - empty-cells
    - filter
    - fit
    - fit-position
    - float
    - float-offset
    - font
    - font-effect
    - font-emphasize
    - font-emphasize-position
    - font-emphasize-style
    - font-family
    - font-size
    - font-size-adjust
    - font-smooth
    - font-stretch
    - font-style
    - font-variant
    - font-weight
    - grid-columns
    - grid-rows
    - hanging-punctuation
    - height
    - hyphenate-after
    - hyphenate-before
    - hyphenate-character
    - hyphenate-lines
    - hyphenate-resource
    - hyphens
    - icon
    - image-orientation
    - image-resolution
    - ime-mode
    - include-source
    - inline-box-align
    - layout-flow
    - left
    - letter-spacing
    - line-break
    - line-height
    - line-stacking
    - line-stacking-ruby
    - line-stacking-shift
    - line-stacking-strategy
    - mark
    - mark-after
    - mark-before
    - marks
    - marquee-direction
    - marquee-play-count
    - marquee-speed
    - marquee-style
    - max-height
    - max-width
    - min-height
    - min-width
    - move-to
    - nav-down
    - nav-index
    - nav-left
    - nav-right
    - nav-up
    - opacity
    - orphans
    - page
    - page-policy
    - phonemes
    - pitch
    - pitch-range
    - play-during
    - position
    - presentation-level
    - punctuation-trim
    - quotes
    - rendering-intent
    - resize
    - rest
    - rest-after
    - rest-before
    - richness
    - right
    - rotation
    - rotation-point
    - ruby-align
    - ruby-overhang
    - ruby-position
    - ruby-span
    - size
    - speak
    - speak-header
    - speak-numeral
    - speak-punctuation
    - speech-rate
    - stress
    - string-set
    - tab-side
    - table-layout
    - target
    - target-name
    - target-new
    - target-position
    - top
    - unicode-bibi
    - unicode-bidi
    - user-select
    - vertical-align
    - visibility
    - voice-balance
    - voice-duration
    - voice-family
    - voice-pitch
    - voice-pitch-range
    - voice-rate
    - voice-stress
    - voice-volume
    - volume
    - white-space
    - white-space-collapse
    - widows
    - width
    - word-break
    - word-spacing
    - word-wrap
    - writing-mode
    - z-index
  name: "Supported CSS Properties"
  type: list

TAG_TYPES:
  default:
    - Rating
    - Warning
    - Category
    - Media
    - Fandom
    - Relationship
    - Character
    - Freeform
    - Banned
  name: "Tag Types"
  type: list
USER_DEFINED_TAG_TYPES:
  default:
    - Fandom
    - Character
    - Relationship
    - Freeform
  name: "User Defined Tag Types"
  type: list

#Indexing
INDEX_BATCH_SIZE:
 name: "Index Batch Size"
 default: 1000
 type: integer

DELIMITER_FOR_INPUT:
 name: "Delimiter For Input"
 default: ','

# validates_format_of :name, in app/models/tag.rb
DELIMITER_FOR_OUTPUT:
 name: "Delimiter For Output"
 default: ', '

#Caching
CACHED_CLASSES:
 name: Cached Classes
 default: ['Work', 'Tag', 'User', 'Pseud', 'Collection']
 type: list

# production caching
#PRODUCTION_CACHE: "memory"
PRODUCTION_CACHE:
 name: "Production Cache Method (memcache or memory)"
 default: memcache

# how long we cache autocomplete search results in minutes
AUTOCOMPLETE_EXPIRATION_TIME:
 name: "Autocomplete Expire Time"
 default: 10
 type: integer

# how many cache pages to expire for a tag/collection/pseud when a work is updated or deleted
PAGES_TO_CACHE:
 name: "Pages To Cache"
 default: 5
 type: integer

# Help directory, must be in the public folder.
# Create subfolders for each supported language
# (eg, /help/fr/ contains the French versions of the help)
HELP_DIRECTORY:
 name: "Help Directory"
 default: /help

RATING_CATEGORY_NAME:
 name: "Rating Cat Name Directory"
 default: Rating

RATING_DEFAULT_TAG_NAME:
 name: "NR Tag Name"
 default: Not Rated

RATING_EXPLICIT_TAG_NAME:
 name: "Explicit Tag Name"
 default: Explicit

RATING_MATURE_TAG_NAME:
 name: "Mature Tag Name"
 default: Mature

CATEGORY_CATEGORY_NAME:
  default: Category
  name: "Category Category Name"

RATING_GENERAL_TAG_NAME:
  default: "General Audiences"
  name: "General Tag Name"

RATING_TEEN_TAG_NAME:
  default: "Teen And Up Audiences"
  name: "Teen Tag Name"

CATEGORY_FEMSLASH_TAG_NAME:
  default: F/F
  name: "Femslash Tag Name"

CATEGORY_GEN_TAG_NAME:
  default: Gen
  name: "Gen Tag Name"

CATEGORY_HET_TAG_NAME:
  default: F/M
  name: "Het Tag Name"

CATEGORY_SLASH_TAG_NAME:
  default: M/M
  name: "Slash Tag Name"

CATEGORY_MULTI_TAG_NAME:
  default: Multi
  name: "Multi Tag Name"

CATEGORY_OTHER_TAG_NAME:
  default: other
  name: "Other Tag Name"

MEDIA_CATEGORY_NAME:
  default: Media
  name: "Media Category Name"

MEDIA_NO_TAG_NAME:
  default: "No Media"
  name: "No Media Tag Name"

MEDIA_UNCATEGORIZED_NAME:
  default: "Uncategorized Fandoms"
  name: "Uncategorized Media Name"

BANNED_CATEGORY_NAME:
  default: Banned
  name: "Banned Category Name"

CHARACTER_CATEGORY_NAME:
  default: Character
  name: "Character Category Name"

COMMON_CATEGORY_NAME:
  default: Common
  name: "Common Category Name"

FANDOM_CATEGORY_NAME:
  default: Fandom
  name: "Fandom Category Name"

FANDOM_NO_TAG_NAME:
  default: "No Fandom"
  name: "No Fandom Tag Name"

FREEFORM_CATEGORY_NAME:
  default: "Additional Tags"
  name: "Freform Category Name"

RELATIONSHIP_CATEGORY_NAME:
  default: Relationship
  name: "Relationship Category Name"

SEARCH_TIPS:
  default:
    - "arthur merlin words>1000 sort hits"
  name: "Search Tips"
  type: list